/* CONFIG.JS — Trilingual Educational Baijiu & Chinese Wine Website */

export const IMAGES = {
  home_banner: "images/home_banner.jpeg",
  fermentation: "images/baijiu_fermentation.png",
  landscape: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  plant: "https://www.wsetglobal.com/media/9396/1608x900_sorghum_baijiu.jpg?anchor=center&mode=crop&width=1608&height=900&rnd=132832647090000000",
  moutai: "https://www.barnews.ch/wp-content/uploads/Kweichow-Moutai.jpg",
  cultural: "https://www.shutterstock.com/image-photo/baijiu-chinese-liquor-grain-600nw-2724793233.jpg",
  castle: "images/castle.png",
  exhibition: "images/exibition.jpeg",
  event: "https://img.12go.asia/0/plain/s3://12go-web-static/static/images/upload-media/1843.jpg",
  map: "images/china.png",
  temple: "https://magazine-fr.wein.plus/uploads/media/magazine_news/194100/conversions/detail.jpg",
  changyu: "https://asialyst.com/fr/wp-content/uploads/2016/07/CHINE-VIN-YANTAI.jpg",
  wineBottle: "https://images.unsplash.com/photo-1670065921509-d0e0d053355b?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
  sorghum: "https://spiritsselection.com/app/uploads/A7069CAF-4534-4D83-AD32-567E63C9D05B_L0_001.jpg",
  paris: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?crop=entropy&cs=srgb&fm=jpg&w=1800&q=85",
};

const IMG = (id) => `https://images.unsplash.com/photo-${id}?crop=entropy&cs=srgb&fm=jpg&w=1600&q=85`;
export const POOL_B = {
  a: IMG("1558618666-fcd25c85cd64"),
  b: IMG("1547595628-c61a29f496f0"),
  c: IMG("1569949381669-ecf31ae8e613"),
  d: IMG("1583623025817-d180a2221d0a"),
  e: IMG("1505935428862-770b6f24f629"),
  f: IMG("1508804185872-d7badad00f7d"),
  g: IMG("1545048702-79362596cdc9"),
  h: IMG("1684606308245-a4784b99cea2"),
};
export const POOL_W = {
  a: IMG("1510972527921-ce03766a1cf1"),
  b: IMG("1726981897998-e9e7d981e26a"),
  c: IMG("1684606308245-a4784b99cea2"),
  d: IMG("1547595628-c61a29f496f0"),
  e: IMG("1569949381669-ecf31ae8e613"),
  f: IMG("1506377247377-2a5b3b417ebb"),
};

export const CONTACT = { email: "contact@nomdusite.com", phone: "+33 6 00 00 00 00" };

export const T = {
en: {
  nav: { home:"Home", who:"About", baijiu:"Baijiu", wine:"Chinese Wine", expositions:"Exhibition", academie:"Academy", events:"Events", contact:"Contact", cta:"Explore", programme:"Programme" },
  home: {
    overline: "China · Spirits · Culture",
    headline: "The World's Most Consumed Spirit,\nFinally Explained.",
    subhead: "Global Spirits & Wine Experience Center is a unique cultural venue bringing together some of the world’s most prestigious spirits. We are honored to showcase Chinese alcoholic beverages through the House of Baijiu and Chinese Wine, an international, non-profit educational association. Our establishment also serves as a showroom dedicated to baijiu, this millennia-old spirit with more than 1,000 years of history, as well as to wines that reflect the richness and diversity of China’s terroirs.",
    cta: "Explore Baijiu", ctaWine: "Chinese Wines",
    stats: [
      { num:"5,000+", label:"Years of history" },
      { num:"11", label:"Official aroma types" },
      { num:"14", label:"Major producing regions" },
      { num:"#1", label:"Spirit by global volume" },
    ],
    introOverline: "What is Baijiu?",
    introTitle: "China's national spirit — and the world's best-kept secret.",
    introBody: "Baijiu (白酒) is a distilled spirit produced primarily from sorghum using solid-state fermentation that dates back over a millennium. Despite being consumed in greater volume than any other spirit on Earth, it remains largely unknown outside China. This site aims to change that.",
    pillarsOverline: "Areas of Study",
    pillars: [
      { icon:"🏺", title:"Aroma Types", desc:"11 officially recognized aromatic families, each tied to a region, a grain, and a fermentation method.", to:"/baijiu" },
      { icon:"🗺️", title:"Regions", desc:"From Guizhou to Shandong — 14 major producing provinces with distinct terroirs.", to:"/baijiu" },
      { icon:"📖", title:"History", desc:"5,000 years of fermentation culture — from imperial courts to modern global markets.", to:"/who-we-are" },
    ],
    timelineOverline: "Historical Timeline",
    timelineTitle: "5,000 years of Baijiu.",
    timeline: [
      { year:"3000 BCE", event:"First evidence of grain fermentation in China — clay vessels with sorghum and rice residue found in Shaanxi." },
      { year:"200 BCE", event:"Han Dynasty establishes official state alcohol monopoly. Early distillation techniques develop." },
      { year:"960 CE", event:"Song Dynasty sees widespread production of qu (曲), the fermentation starter that defines Baijiu's complexity." },
      { year:"1368", event:"Ming Dynasty — distillation technology matures. Sorghum becomes dominant. Regional styles diverge." },
      { year:"1704", event:"Kweichow Moutai distillery precursor founded in Maotai village, Guizhou. Sauce aroma tradition born." },
      { year:"1915", event:"Moutai wins gold at the Panama-Pacific International Exposition — first international recognition." },
      { year:"1952", event:"First National Baijiu Competition classifies four aroma types: Sauce, Strong, Light, Rice." },
      { year:"1989", event:"Classification expands to 11 official aroma types, reflecting regional diversity." },
      { year:"2012", event:"Baijiu becomes the world's best-selling spirit by volume, overtaking vodka." },
    ],
  },
  who: {
    overline:"About",
    title:"An independent educational resource on Chinese spirits and wines.",
    lead:"This site was created to fill a gap: despite Baijiu being the world's most consumed spirit, quality educational content in Western languages remains scarce. We document aroma types, regions, producers, and history with factual accuracy.",
    missionTitle:"Our Educational Mission",
    mission:"We believe that understanding Baijiu requires understanding China — its geography, agriculture, cultural rituals, and culinary traditions. This site approaches the subject the way a serious reference work would: factual, structured, and without commercial bias.",
    whatTitle:"What is Baijiu?",
    whatBody:"Baijiu is a distilled spirit made primarily from sorghum, fermented using qu (曲) — a culture of molds, bacteria, and yeast compacted into bricks or balls. The fermentation happens in solid or semi-solid state, unlike the liquid fermentation used in Western spirits. This produces an extraordinarily complex aromatic profile with hundreds of flavor compounds not found in whisky, vodka, or gin.",
    vsTitle:"Baijiu vs. Other Spirits",
    vs:[
      { label:"vs. Whisky", body:"Both are grain-based and aged, but Baijiu uses solid-state fermentation with qu cultures, producing far more aromatic complexity. ABV typically 40–65%." },
      { label:"vs. Vodka", body:"Vodka prioritizes neutrality through repeated distillation. Baijiu does the opposite — it amplifies the fermentation character, producing hundreds of identifiable aromatic compounds." },
      { label:"vs. Cognac", body:"Both are refined prestige spirits with protected regional designations. But Baijiu's fermentation science is entirely distinct — no grapes, no pot stills, no wood aging in most styles." },
    ],
    riseTitle:"The Rise of Chinese Wines",
    riseBody:"China is now the 6th largest wine-producing country by volume. Regions like Ningxia, Yunnan, and Shandong produce internationally awarded wines. The 2011 Decanter Asia Wine Awards launched Helan Qingxue's Jia Bei Lan to global attention — a turning point for Chinese wine credibility.",
    timelineTitle:"Baijiu Through History",
  },
  baijiu: {
    overline:"Baijiu · 白酒",
    title:"The 11 Aroma Types of Baijiu",
    lead:"Chinese national standards recognize 11 official aroma types (香型, xiānɡ xíng). Each is tied to a region, a fermentation method, a grain composition, and a set of chemical markers. Filter by region to explore which aroma types are produced where.",
    regionFilter:"Filter by Region",
    allRegions:"All Regions",
    aromasTitle:"Aroma Types",
    regions:["Guizhou","Sichuan","Jiangsu","Anhui","Henan","Shanxi","Beijing","Hebei","Guangxi","Shaanxi","Hubei","Shandong","Hunan","Jiangxi"],
    producersTitle:"Key Producers",
  },
  wine: {
    overline:"Chinese Wine · 中国葡萄酒",
    title:"China's Wine Regions",
    lead:"China has been producing wine for over 2,000 years, but the modern industry took shape in the 1980s. Today, twelve key wine regions produce internationally recognized wines across a range of styles and climates.",
  },
  expositions: {
    overline:"Exhibition",
    title:"Paris Wine & Baijiu 2024",
    lead:"The landmark exhibition bringing Chinese spirits and wines to European connoisseurs.",
    heroBody:"Held in Paris in October 2024, the Paris Wine & Baijiu exhibition gathered over 40 producers from China's leading Baijiu and wine regions for a four-day event attended by sommeliers, importers, journalists, and collectors from across Europe. The exhibition featured educational masterclasses, blind tasting sessions, and a dedicated conference program on the history and science of Baijiu fermentation.",
    section1Title:"Format & Program",
    section1Body:"The event was structured around three core formats: a public tasting salon open to all visitors, professional buyer sessions by appointment, and an evening conference series with Chinese and European experts presenting on aroma type classification, the Chinese wine terroir landscape, and the cultural significance of Baijiu in contemporary China.",
    section2Title:"Educational Focus",
    section2Body:"A central feature of the 2024 edition was the Aroma Type Discovery Lab — a guided sensory experience allowing visitors to smell and taste across all 11 official Baijiu aroma types side by side. Conducted by trained educators, the sessions ran continuously throughout the event and were consistently oversubscribed.",
    section3Title:"2025 Edition",
    section3Body:"The 2025 edition is in planning, with an expanded program including a dedicated Chinese wine masterclass track and the first European Baijiu cocktail competition.",
  },
  events: {
    overline:"Events",
    title:"Events & Brand Highlights",
    lead:"Festivals, tastings, and brand showcases dedicated to Chinese spirits and wines.",
    changyu: {
      overline:"Brand Spotlight",
      title:"Changyu: 130 Years of Chinese Wine Excellence",
      body:"Founded in 1892 by Zhang Bishi in Yantai, Shandong, Changyu Pioneer Wine is the oldest and largest wine company in China. With over 130 years of continuous production, Changyu has pioneered every major chapter of Chinese wine history — from importing French varietal cuttings in the 1890s, to earning international recognition at early 20th century world fairs, to today producing award-winning wines across 7 regions.",
      bodyExtra:"Changyu was the first Chinese winery to introduce Western wine-making techniques at scale. Today, the company's portfolio spans Cabernet Sauvignon, Chardonnay, Ice Wine, Brandy, and sparkling wine — produced across estates in Shandong, Xinjiang, Ningxia, Liaoning, Shaanxi, and beyond. Changyu's century-old underground wine cellar in Yantai is a classified cultural heritage site and receives over 200,000 visitors annually.",
      stats:[
        { num:"1892", label:"Year founded" },
        { num:"7", label:"Wine regions" },
        { num:"130+", label:"Years of production" },
      ],
    },
    otherEvents: [
      { title:"Chengdu Baijiu Festival", date:"March 2024", desc:"Annual celebration in the capital of Strong Aroma Baijiu, featuring the top 20 Sichuan distilleries." },
      { title:"Ningxia Wine Harvest", date:"September 2024", desc:"Harvest season open days at Ningxia's leading estates including Helan Qingxue, Silver Heights, and Tiansai." },
      { title:"Beijing Baijiu Week", date:"November 2024", desc:"Week-long educational program at the National Museum of China covering Baijiu history, production, and culture." },
    ],
  },
  academie: {
    overline:"Academy",
    title:"Learning Resources",
    lead:"Curated educational content: video series, tasting guides, and expert presentations on Baijiu and Chinese wines.",
    guides: [
      { title:"Beginner's Guide to Baijiu", desc:"An introduction to the world's most consumed spirit — how it's made, the main aroma types, and how to approach it as a newcomer.", tag:"GUIDE" },
      { title:"Understanding Qu (曲)", desc:"The fermentation starter that defines all Chinese distilled spirits. A deep dive into its microbiology and its effect on aroma.", tag:"SCIENCE" },
      { title:"Chinese Wine Regions Overview", desc:"A structured overview of China's 12 key wine regions — geography, climate, and flagship producers for each.", tag:"WINE" },
      { title:"How to Taste Baijiu", desc:"Practical tasting methodology — nosing, palate assessment, finish, and how to track personal notes across aroma types.", tag:"TASTING" },
      { title:"Baijiu in Chinese Culture", desc:"The role of Baijiu in business, family, and ceremony — why it matters beyond what's in the glass.", tag:"CULTURE" },
      { title:"Notable Distilleries, Ranked", desc:"A reference guide to 30+ key distilleries across all 11 aroma types — location, founding date, and flagship expressions.", tag:"REFERENCE" },
    ],
  },
  contact: {
    overline:"Contact",
    title:"Get in Touch",
    lead:"Questions, corrections, or collaboration proposals — we read every message.",
    email:"contact@nomdusite.com",
    phone:"+33 6 00 00 00 00",
  },
  footer: {
    tagline:"An independent educational resource on Baijiu & Chinese wines.",
    navTitle:"Navigation",
    contactTitle:"Contact",
    copy:"© 2024 — Educational Resource on Baijiu & Chinese Wines",
    legal:"Independent · Factual · Non-commercial",
  },
},

fr: {
  nav: { home:"Accueil", who:"À Propos", baijiu:"Baijiu", wine:"Vin Chinois", expositions:"Exposition", academie:"Académie", events:"Événements", contact:"Contact", cta:"Explorer", programme:"Programme" },
  home: {
    overline: "Chine · Spiritueux · Culture",
    headline: "Le spiritueux le plus consommé au monde,\nenfin expliqué.",
    subhead: "Global Spirits & Wine Experience Center est un lieu culturel unique rassemblant les plus grands alcools de prestige du monde. Nous avons l’honneur de mettre à l’honneur les alcools chinois à travers la Maison du Baijiu et du Vin Chinois, un centre international d’éducation associatif et non lucratif. Notre établissement est également une showroom dédiée au baijiu, ce spiritueux millénaire (plus de 1000 ans d’histoire), ainsi qu’aux vins qui expriment toute la richesse des terroirs chinois.",
    cta: "Explorer le Baijiu", ctaWine: "Vins Chinois",
    stats: [
      { num:"5 000+", label:"Ans d'histoire" },
      { num:"11", label:"Types aromatiques officiels" },
      { num:"14", label:"Régions productrices majeures" },
      { num:"N°1", label:"Spiritueux en volume mondial" },
    ],
    introOverline: "Qu'est-ce que le Baijiu ?",
    introTitle: "Le spiritueux national chinois — et le secret le mieux gardé du monde.",
    introBody: "Le Baijiu (白酒) est un spiritueux distillé produit principalement à partir de sorgho grâce à un processus de fermentation à l'état solide qui remonte à plus d'un millénaire. Malgré un volume de consommation supérieur à tout autre spiritueux sur Terre, il reste largement méconnu hors de Chine. Ce site vise à changer cela.",
    pillarsOverline: "Domaines d'étude",
    pillars: [
      { icon:"🏺", title:"Types aromatiques", desc:"11 familles aromatiques officielles, chacune liée à une région, un grain et une méthode de fermentation.", to:"/baijiu" },
      { icon:"🗺️", title:"Régions", desc:"Du Guizhou au Shandong — 14 provinces productrices majeures aux terroirs distinctifs.", to:"/baijiu" },
      { icon:"📖", title:"Histoire", desc:"5 000 ans de culture de fermentation — des cours impériales aux marchés mondiaux.", to:"/who-we-are" },
    ],
    timelineOverline: "Frise chronologique",
    timelineTitle: "5 000 ans de Baijiu.",
    timeline: [
      { year:"3000 av. J.-C.", event:"Premières preuves de fermentation céréalière en Chine — récipients en argile avec résidus de sorgho trouvés dans le Shaanxi." },
      { year:"200 av. J.-C.", event:"La Dynastie Han établit un monopole d'État sur la production d'alcool. Les premières techniques de distillation se développent." },
      { year:"960 ap. J.-C.", event:"La Dynastie Song voit la production généralisée de qu (曲), le ferment qui définit la complexité du Baijiu." },
      { year:"1368", event:"Dynastie Ming — la distillation arrive à maturité. Le sorgho devient dominant. Les styles régionaux divergent." },
      { year:"1704", event:"La distillerie précurseur de Kweichow Moutai est fondée dans le village de Maotai, Guizhou." },
      { year:"1915", event:"Moutai remporte une médaille d'or à l'Exposition Panama-Pacific — première reconnaissance internationale." },
      { year:"1952", event:"Premier concours national de Baijiu : classification en quatre types aromatiques : Sauce, Fort, Léger, Riz." },
      { year:"1989", event:"La classification s'étend à 11 types aromatiques officiels." },
      { year:"2012", event:"Le Baijiu devient le spiritueux le plus vendu au monde en volume." },
    ],
  },
  who: {
    overline:"À Propos",
    title:"Une ressource éducative indépendante sur les spiritueux et vins chinois.",
    lead:"Ce site a été créé pour combler un vide : malgré le Baijiu comme spiritueux le plus consommé au monde, les contenus éducatifs de qualité en langues occidentales restent rares.",
    missionTitle:"Notre mission éducative",
    mission:"Nous croyons que comprendre le Baijiu nécessite de comprendre la Chine — sa géographie, son agriculture, ses rituels culturels et ses traditions culinaires. Ce site aborde le sujet comme un ouvrage de référence sérieux : factuel, structuré, sans biais commercial.",
    whatTitle:"Qu'est-ce que le Baijiu ?",
    whatBody:"Le Baijiu est un spiritueux distillé à base de sorgho, fermenté grâce au qu (曲) — une culture de moisissures, bactéries et levures compactée en briques. La fermentation s'effectue à l'état solide, contrairement aux spiritueux occidentaux. Cela produit un profil aromatique extraordinairement complexe, avec des centaines de composés absents du whisky, vodka ou gin.",
    vsTitle:"Baijiu vs. Autres Spiritueux",
    vs:[
      { label:"vs. Whisky", body:"Les deux sont à base de céréales et vieillis, mais le Baijiu utilise une fermentation à l'état solide avec cultures de qu, produisant une complexité aromatique bien supérieure. Titre alcoométrique : 40–65%." },
      { label:"vs. Vodka", body:"La vodka vise la neutralité par distillation répétée. Le Baijiu fait l'inverse — il amplifie le caractère de fermentation, produisant des centaines de composés aromatiques identifiables." },
      { label:"vs. Cognac", body:"Les deux sont des spiritueux de prestige à appellation protégée. Mais la science de fermentation du Baijiu est entièrement distincte — pas de raisins, pas d'alambics, pas de bois dans la plupart des styles." },
    ],
    riseTitle:"L'essor des vins chinois",
    riseBody:"La Chine est le 6e pays producteur de vin en volume. Les Decanter Asia Wine Awards 2011 ont propulsé le Jia Bei Lan de Helan Qingxue sur la scène mondiale — tournant décisif pour la crédibilité du vin chinois.",
    timelineTitle:"Le Baijiu à travers l'histoire",
  },
  baijiu: {
    overline:"Baijiu · 白酒",
    title:"Les 11 types aromatiques du Baijiu",
    lead:"Les normes nationales chinoises reconnaissent 11 types aromatiques officiels (香型). Chacun est lié à une région, une méthode de fermentation, une composition de grains et des marqueurs chimiques précis. Filtrez par région pour explorer quels types sont produits où.",
    regionFilter:"Filtrer par région",
    allRegions:"Toutes les régions",
    aromasTitle:"Types aromatiques",
    regions:["Guizhou","Sichuan","Jiangsu","Anhui","Henan","Shanxi","Pékin","Hebei","Guangxi","Shaanxi","Hubei","Shandong","Hunan","Jiangxi"],
    producersTitle:"Producteurs clés",
  },
  wine: {
    overline:"Vin Chinois · 中国葡萄酒",
    title:"Les régions viticoles de Chine",
    lead:"La Chine produit du vin depuis plus de 2 000 ans, mais l'industrie moderne a pris forme dans les années 1980. Douze régions viticoles clés produisent aujourd'hui des vins reconnus à l'international.",
  },
  expositions: {
    overline:"Exposition",
    title:"Paris Wine & Baijiu 2024",
    lead:"L'exposition phare réunissant spiritueux et vins chinois pour les connaisseurs européens.",
    heroBody:"Tenu à Paris en octobre 2024, cette exposition a rassemblé plus de 40 producteurs des principales régions de Baijiu et de vin de Chine pour un événement de quatre jours réunissant sommeliers, importateurs, journalistes et collectionneurs de toute l'Europe.",
    section1Title:"Format & Programme",
    section1Body:"L'événement s'articulait autour de trois formats principaux : un salon de dégustation public, des sessions acheteurs professionnels sur rendez-vous, et une série de conférences en soirée avec des experts chinois et européens.",
    section2Title:"Focus éducatif",
    section2Body:"Une expérience sensorielle guidée permettait aux visiteurs de sentir et goûter les 11 types aromatiques officiels du Baijiu côte à côte. Animées par des éducateurs formés, les sessions étaient continuellement complets.",
    section3Title:"Édition 2025",
    section3Body:"L'édition 2025 est en préparation, avec un programme élargi incluant une série de masterclasses sur les vins chinois et le premier concours européen de cocktails au Baijiu.",
  },
  events: {
    overline:"Événements",
    title:"Événements & Marques à l'honneur",
    lead:"Festivals, dégustations et présentations dédiés aux spiritueux et vins chinois.",
    changyu: {
      overline:"Marque à l'honneur",
      title:"Changyu : 130 ans d'excellence viticole chinoise",
      body:"Fondée en 1892 par Zhang Bishi à Yantai, Shandong, Changyu Pioneer Wine est la plus ancienne et la plus grande entreprise vinicole de Chine. Pionnière dans chaque grand chapitre de l'histoire du vin chinois.",
      bodyExtra:"Changyu fut la première cave chinoise à introduire les techniques viticoles occidentales à grande échelle. Aujourd'hui, son portefeuille couvre Cabernet Sauvignon, Chardonnay, Vin de glace, Brandy et mousseux — dans 7 régions. Sa cave centenaire de Yantai est classée patrimoine culturel.",
      stats:[
        { num:"1892", label:"Année de fondation" },
        { num:"7", label:"Régions viticoles" },
        { num:"130+", label:"Années de production" },
      ],
    },
    otherEvents: [
      { title:"Festival Baijiu de Chengdu", date:"Mars 2024", desc:"Célébration annuelle dans la capitale du Baijiu Fort, réunissant les 20 meilleures distilleries du Sichuan." },
      { title:"Vendanges de Ningxia", date:"Septembre 2024", desc:"Journées portes ouvertes lors des vendanges dans les domaines phares de Ningxia : Helan Qingxue, Silver Heights et Tiansai." },
      { title:"Semaine Baijiu de Pékin", date:"Novembre 2024", desc:"Programme éducatif au Musée National de Chine sur l'histoire, la production et la culture du Baijiu." },
    ],
  },
  academie: {
    overline:"Académie",
    title:"Ressources pédagogiques",
    lead:"Contenus éducatifs sélectionnés : séries vidéo, guides de dégustation et présentations d'experts sur le Baijiu et les vins chinois.",
    guides: [
      { title:"Guide du débutant au Baijiu", desc:"Une introduction au spiritueux le plus consommé du monde — fabrication, types aromatiques et conseils pour les novices.", tag:"GUIDE" },
      { title:"Comprendre le Qu (曲)", desc:"Le ferment qui définit tous les spiritueux distillés chinois. Plongée dans sa microbiologie et son effet sur les arômes.", tag:"SCIENCE" },
      { title:"Vue d'ensemble des régions viticoles chinoises", desc:"Présentation structurée des 12 régions viticoles clés de Chine — géographie, climat et producteurs phares.", tag:"VIN" },
      { title:"Comment déguster le Baijiu", desc:"Méthodologie de dégustation pratique — nez, bouche, finale et prise de notes personnelles sur les types aromatiques.", tag:"DÉGUSTATION" },
      { title:"Le Baijiu dans la culture chinoise", desc:"Le rôle du Baijiu dans les affaires, la famille et les cérémonies — pourquoi il importe bien au-delà du contenu du verre.", tag:"CULTURE" },
      { title:"Les distilleries notables, classées", desc:"Guide de référence sur 30+ distilleries clés dans tous les types aromatiques — localisation, date de fondation et expressions phares.", tag:"RÉFÉRENCE" },
    ],
  },
  contact: {
    overline:"Contact",
    title:"Nous contacter",
    lead:"Questions, corrections ou propositions de collaboration — nous lisons chaque message.",
    email:"contact@nomdusite.com",
    phone:"+33 6 00 00 00 00",
  },
  footer: {
    tagline:"Une ressource éducative indépendante sur le Baijiu & les vins chinois.",
    navTitle:"Navigation",
    contactTitle:"Contact",
    copy:"© 2024 — Ressource éducative sur le Baijiu & les vins chinois",
    legal:"Indépendant · Factuel · Non-commercial",
  },
},

zh: {
  nav: { home:"首页", who:"关于", baijiu:"白酒", wine:"中国葡萄酒", expositions:"展览", academie:"学院", events:"活动", contact:"联系", cta:"探索", programme:"活动项目" },
  home: {
    overline: "中国 · 烈酒 · 文化",
    headline: "全球消费量第一的烈酒，\n终于有了完整解读。",
    subhead: "全球烈酒与葡萄酒体验中心（Global Spirits & Wine Experience Center） 是一个独特的文化场所，汇聚了世界上最具声望的高端酒类。我们十分荣幸通过 中国白酒与葡萄酒之家（一个国际性、非营利性的教育机构）向公众展示中国酒文化。<br> 本中心同时也是一个专注于 白酒 的展示空间。白酒拥有逾千年的悠久历史，是中国传统蒸馏酒的杰出代表。此外，我们还展示能够充分体现中国风土特色与地域魅力的葡萄酒，呈现中国酒业的丰富多样性。",
    cta: "探索白酒", ctaWine: "中国葡萄酒",
    stats: [
      { num:"5000+", label:"年历史" },
      { num:"11", label:"官方香型" },
      { num:"14", label:"主要产区" },
      { num:"第一", label:"全球销量烈酒" },
    ],
    introOverline: "什么是白酒？",
    introTitle: "中国国家烈酒——世界上最鲜为人知的秘密。",
    introBody: "白酒是一种主要以高粱为原料酿造的蒸馏酒，采用固态发酵工艺，历史可追溯至一千多年前。尽管其消费量超过地球上任何其他烈酒，它在中国以外仍鲜为人知。本网站旨在改变这一现状。",
    pillarsOverline: "研究领域",
    pillars: [
      { icon:"🏺", title:"香型", desc:"11种官方认可的香型，每种都与一个地区、一种粮食和一种发酵方法相关联。", to:"/baijiu" },
      { icon:"🗺️", title:"产区", desc:"从贵州到山东——14个主要产酒省份，各具独特风土。", to:"/baijiu" },
      { icon:"🍷", title:"中国葡萄酒", desc:"宁夏、云南、山东——中国新兴葡萄酒产区正与国际标准比肩。", to:"/chinese-wine" },
      { icon:"📖", title:"历史", desc:"五千年发酵文化——从皇家宫廷到现代全球市场。", to:"/who-we-are" },
    ],
    timelineOverline: "历史年表",
    timelineTitle: "白酒五千年。",
    timeline: [
      { year:"公元前3000年", event:"中国最早的谷物发酵证据——在陕西发现带有高粱和大米残留物的陶罐。" },
      { year:"公元前200年", event:"汉朝建立官方酒类专卖制度。早期蒸馏技术开始发展。" },
      { year:"公元960年", event:"宋朝曲（酒曲）的生产得到广泛推广，这是定义白酒复杂性的发酵剂。" },
      { year:"1368年", event:"明朝——蒸馏技术趋于成熟。高粱成为主要粮食原料。各地风格开始分化。" },
      { year:"1704年", event:"茅台酒前身蒸馏厂在贵州茅台村建立。酱香型传统由此诞生。" },
      { year:"1915年", event:"茅台酒在巴拿马太平洋国际博览会上荣获金奖——首次获得国际认可。" },
      { year:"1952年", event:"第一届全国白酒品评会正式确立四大香型：酱香、浓香、清香、米香。" },
      { year:"1989年", event:"分类扩展至11种官方香型，体现地区多样性。" },
      { year:"2012年", event:"白酒成为全球销量最大的烈酒，超越伏特加。" },
    ],
  },
  who: {
    overline:"关于",
    title:"关于中国烈酒与葡萄酒的独立教育资源。",
    lead:"本网站的创建是为了填补一个空白：尽管白酒是全球消费量最大的烈酒，但西方语言中优质的教育内容仍然匮乏。",
    missionTitle:"我们的教育使命",
    mission:"我们相信，理解白酒需要理解中国——其地理、农业、文化礼仪和饮食传统。本网站以严肃参考著作的方式来处理这一主题：事实性、结构化、无商业偏见。",
    whatTitle:"什么是白酒？",
    whatBody:"白酒是一种主要以高粱为原料，通过曲（各种霉菌、细菌和酵母的混合物）发酵而成的蒸馏酒。发酵过程在固态或半固态状态下进行，与西方烈酒的液态发酵截然不同。这产生了极其复杂的芳香特征，含有数百种在威士忌、伏特加或金酒中找不到的风味化合物。",
    vsTitle:"白酒与其他烈酒的对比",
    vs:[
      { label:"vs. 威士忌", body:"两者都以谷物为基础并经过陈酿，但白酒使用固态发酵和曲文化，产生更丰富的芳香复杂性。酒精度通常在40-65%之间。" },
      { label:"vs. 伏特加", body:"伏特加通过反复蒸馏追求中性。白酒则相反——它颂扬并放大发酵特性，产生数百种可识别的芳香化合物。" },
      { label:"vs. 干邑", body:"两者都是有受保护地区标志的精致高档烈酒。但白酒的发酵科学完全不同——没有葡萄，没有壶式蒸馏器，大多数风格也没有橡木桶陈酿。" },
    ],
    riseTitle:"中国葡萄酒的兴起",
    riseBody:"中国现在是全球第六大葡萄酒产量国。2011年醇鉴亚洲葡萄酒大赛将贺兰晴雪的加贝兰推向了全球舞台——这是中国葡萄酒可信度的重要转折点。",
    timelineTitle:"白酒历史年表",
  },
  baijiu: {
    overline:"白酒",
    title:"白酒的11种香型",
    lead:"中国国家标准认定11种官方香型。每种香型都与一个产区、一种发酵方法、一种粮食组成和一组化学标志物相关联。按产区筛选，探索各地生产的香型。",
    regionFilter:"按产区筛选",
    allRegions:"全部产区",
    aromasTitle:"香型",
    regions:["贵州","四川","江苏","安徽","河南","山西","北京","河北","广西","陕西","湖北","山东","湖南","江西"],
    producersTitle:"主要酿造商",
  },
  wine: {
    overline:"中国葡萄酒",
    title:"中国葡萄酒产区",
    lead:"中国生产葡萄酒已有2000多年的历史，但现代葡萄酒产业在1980年代才开始成型。如今，十二个主要葡萄酒产区出产获得国际认可的各种风格葡萄酒。",
  },
  expositions: {
    overline:"展览",
    title:"2024巴黎葡萄酒与白酒展",
    lead:"将中国烈酒与葡萄酒带给欧洲鉴赏家的重要展览。",
    heroBody:"2024年10月在巴黎举办，汇聚了来自中国白酒和葡萄酒主要产区的40多家生产商，吸引了来自欧洲各地的侍酒师、进口商、记者和收藏家参加为期四天的活动。",
    section1Title:"形式与议程",
    section1Body:"活动围绕三种核心形式展开：面向所有访客开放的公开品鉴沙龙、预约制专业买家会议，以及由中欧专家主讲的系列晚间讲座。",
    section2Title:"教育重点",
    section2Body:"本届展览的核心亮点是\"香型探索实验室\"——一项引导性感官体验，让访客能够并排闻、尝11种官方白酒香型。由受训教育者主持的会议全程持续进行，场场爆满。",
    section3Title:"2025年版",
    section3Body:"2025年版正在筹备中，计划推出扩大的中国葡萄酒大师课系列和首届欧洲白酒鸡尾酒大赛。",
  },
  events: {
    overline:"活动",
    title:"活动与品牌聚焦",
    lead:"致力于中国烈酒与葡萄酒的节日、品鉴会和品牌展示。",
    changyu: {
      overline:"品牌聚焦",
      title:"张裕：130年中国葡萄酒卓越历程",
      body:"张裕葡萄酒于1892年由张弼士在山东烟台创立，是中国历史最悠久、规模最大的葡萄酒企业。经过130多年的持续生产，张裕引领了中国葡萄酒历史的每一个重要篇章。",
      bodyExtra:"张裕是第一家大规模引进西方酿酒技术的中国酒庄。今天，公司的产品组合涵盖赤霞珠、霞多丽、冰酒、白兰地和起泡酒——在7个产区生产。其位于烟台的百年地下酒窖被列为文化遗产，每年吸引逾20万名游客。",
      stats:[
        { num:"1892", label:"创立年份" },
        { num:"7", label:"葡萄酒产区" },
        { num:"130+", label:"年生产历史" },
      ],
    },
    otherEvents: [
      { title:"成都白酒节", date:"2024年3月", desc:"在浓香型白酒之都举办的年度盛会，汇聚四川最顶尖的20家蒸馏厂。" },
      { title:"宁夏葡萄采收节", date:"2024年9月", desc:"宁夏主要酒庄开放日，包括贺兰晴雪、银色高地和天塞。" },
      { title:"北京白酒周", date:"2024年11月", desc:"中国国家博物馆举办的为期一周的教育活动，涵盖白酒历史、生产和文化。" },
    ],
  },
  academie: {
    overline:"学院",
    title:"学习资源",
    lead:"精选教育内容：关于白酒和中国葡萄酒的视频系列、品鉴指南和专家讲座。",
    guides: [
      { title:"白酒初学者指南", desc:"全球消费量最大烈酒的入门介绍——酿造方法、主要香型及新手建议。", tag:"指南" },
      { title:"理解曲（酒曲）", desc:"定义所有中国蒸馏烈酒的发酵剂。深入探讨其微生物学及对香气的影响。", tag:"科学" },
      { title:"中国葡萄酒产区综览", desc:"中国12个主要葡萄酒产区的结构化概述——地理、气候和各地旗舰生产商。", tag:"葡萄酒" },
      { title:"如何品鉴白酒", desc:"实用品鉴方法论——嗅觉、口感评估、余味以及如何记录各香型的个人笔记。", tag:"品鉴" },
      { title:"白酒在中国文化中的地位", desc:"白酒在商业、家庭和仪式中的角色——为什么它的意义远超杯中之物。", tag:"文化" },
      { title:"著名蒸馏厂排名", desc:"涵盖所有11种香型的30多家主要蒸馏厂参考指南——位置、建立年份和旗舰产品。", tag:"参考" },
    ],
  },
  contact: {
    overline:"联系",
    title:"联系我们",
    lead:"问题、更正或合作建议——我们阅读每一封消息。",
    email:"contact@nomdusite.com",
    phone:"+33 6 00 00 00 00",
  },
  footer: {
    tagline:"关于白酒与中国葡萄酒的独立教育资源。",
    navTitle:"导航",
    contactTitle:"联系",
    copy:"© 2024 — 白酒与中国葡萄酒教育资源",
    legal:"独立 · 客观 · 非商业",
  },
},

};